### ISSUE TITLE
Helm: use `Secret` manifest to store `appId` & `installationId`

### ISSUE THREAD

**Issue by gg-vara** [Qalisa/github-actions-secrets-operator#5]
Actually, if using Ansible, we have to do someting exotic like this to use this chart:

```
- name: Install github-actions-secrets-operator w/ Helm
  kubernetes.core.helm:
    name: github-actions-secrets-operator
    chart_ref: qalisa-ghaso/github-actions-secrets-operator
    release_namespace: "{{ k8s__github_actions_secrets_operator__namespace }}"
    create_namespace: false
    wait: true
    set_values:
      - value: github.appId={{ github_actions_secrets_operator__github_app__app_id }}
        value_type: string
      - value: github.installationId={{ github_actions_secrets_operator__github_app__installation_id }}
        value_type: string
    values:
      github:
        privateKey:
          explicit: "{{ github_actions_secrets_operator__github_app__priv_key }}"

```

The classic way to go is also to expect `appId` and `installationId` in an already existing Secret in cluster; it would prevent unexpected YAML Helm cast (https://helm.sh/docs/chart_best_practices/values/#make-types-clear)
